"""Read-only SQLite snapshot to new PostgreSQL service schema; never copies accounts.

Run with service sources stopped at cutover. Refuses any nonempty destination table.
All schema creation, COPY and row comparison are one PostgreSQL transaction.
"""
import argparse,sqlite3,re,sys,json
from pathlib import Path
from collections import Counter
import psycopg
from psycopg import sql
from psycopg.rows import dict_row
import yaml,os
ACCOUNT={'users','teams','roles','sessions','login_attempts'}

def ident(name):return '"'+name.replace('"','""')+'"'
def pieces(body):
 result=[];start=depth=0;quote=None;i=0
 while i<len(body):
  ch=body[i]
  if quote:
   if ch==quote:
    if i+1<len(body) and body[i+1]==quote:i+=1
    else:quote=None
  elif ch in "'\"":quote=ch
  elif ch=='(':depth+=1
  elif ch==')':depth-=1
  elif ch==',' and depth==0:result.append(body[start:i]);start=i+1
  i+=1
 result.append(body[start:]);return result

def migrate(source,config,dry_run=False):
 cfg=yaml.safe_load(Path(config).read_text())['database'];schema=cfg['schema']
 if schema not in {'wianews','wiacoding'}:raise ValueError('Unexpected service schema')
 original=sqlite3.connect(Path(source).resolve().as_uri()+'?mode=ro',uri=True)
 original.row_factory=sqlite3.Row;original.execute('BEGIN')
 tables=[r for r in original.execute("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'") if r['name'] not in ACCOUNT]
 password=os.environ[cfg['password_env']] if cfg.get('password_env') else cfg.get('password','')
 with psycopg.connect(host=cfg['host'],port=cfg['port'],dbname=cfg['name'],user=cfg['user'],password=password,sslmode=cfg.get('sslmode','prefer'),row_factory=dict_row) as pg:
  pg.execute('SELECT pg_advisory_xact_lock(741902631)')
  # Do not guess account matches: require every old user to have the same employee/ID.
  for user in original.execute('SELECT user_id,employee_id FROM users'):
   match=pg.execute('SELECT user_id FROM platform.users WHERE lower(employee_id)=lower(%s)',(user['employee_id'],)).fetchone()
   if not match or match['user_id']!=user['user_id']:raise RuntimeError('Account mapping mismatch; migrate platform accounts first')
  pg.execute(sql.SQL('CREATE SCHEMA IF NOT EXISTS {}').format(sql.Identifier(schema)))
  pg.execute(sql.SQL('SET LOCAL search_path TO {},platform,pg_catalog').format(sql.Identifier(schema)))
  pg.execute("CREATE COLLATION IF NOT EXISTS nocase (provider=icu, locale='und-u-ks-level2', deterministic=false)")
  ddl=["CREATE COLLATION IF NOT EXISTS nocase (provider=icu, locale='und-u-ks-level2', deterministic=false);"];foreign=[]
  for row in tables:
   name=row['name'];body=row['sql'][row['sql'].index('(')+1:row['sql'].rindex(')')]
   parts=[]
   for part in pieces(body):
    if re.match(r'\s*(?:CONSTRAINT\s+\w+\s+)?FOREIGN KEY',part,re.I):continue
    part=re.sub(r'\s+REFERENCES\s+[\w".]+\s*\([^)]*\)(?:\s+ON\s+(?:DELETE|UPDATE)\s+(?:CASCADE|RESTRICT|SET NULL|SET DEFAULT|NO ACTION))*','',part,flags=re.I)
    part=re.sub(r'\bREAL\b','DOUBLE PRECISION',part,flags=re.I)
    part=re.sub(r'json_type\((\w+)\)',r'jsonb_typeof(\1::jsonb)',part)
    part=re.sub(r'json_array_length\((\w+)\)',r'jsonb_array_length(\1::jsonb)',part)
    part=re.sub(r'json_valid\((\w+)\)',r'(\1 IS JSON)',part)
    # SQLite TEXT PRIMARY KEY technically allows NULL; actual data has none.
    parts.append(part)
   if name in {'sample_runs','prompt_edit_turns'}:parts.append('entry_seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE')
   create='CREATE TABLE IF NOT EXISTS '+ident(name)+' ('+','.join(parts)+')'
   pg.execute(create);ddl.append(create+';')
   if pg.execute(sql.SQL('SELECT count(*) AS n FROM {}').format(sql.Identifier(name))).fetchone()['n']:raise RuntimeError(f'Destination {schema}.{name} is not empty; refusing overwrite')
   fks={}
   for fk in original.execute('PRAGMA foreign_key_list('+ident(name)+')'):fks.setdefault(fk['id'],[]).append(fk)
   for number,group in fks.items():
    group.sort(key=lambda f:f['seq']);fk=group[0];target=fk['table'];target_schema='platform' if target in ACCOUNT else schema
    columns=','.join(ident(f['from']) for f in group);refs=','.join(ident(f['to']) for f in group)
    foreign.append('ALTER TABLE '+ident(name)+' ADD CONSTRAINT '+ident(name+'_fk_'+str(number))+' FOREIGN KEY ('+columns+') REFERENCES '+ident(target_schema)+'.'+ident(target)+' ('+refs+') ON DELETE '+fk['on_delete']+' ON UPDATE '+fk['on_update']+' DEFERRABLE INITIALLY DEFERRED;')
  for row in tables:
   name=row['name'];records=original.execute('SELECT * FROM '+ident(name)).fetchall();columns=[r['name'] for r in original.execute('PRAGMA table_info('+ident(name)+')')]
   if name in {'sample_runs','prompt_edit_turns'}:
    records=original.execute('SELECT *,rowid AS entry_seq FROM '+ident(name)).fetchall();columns.append('entry_seq')
   with pg.cursor().copy(sql.SQL('COPY {} ({}) FROM STDIN').format(sql.Identifier(name),sql.SQL(',').join(map(sql.Identifier,columns)))) as copy:
    for record in records:copy.write_row(tuple(record))
   if name in {'sample_runs','prompt_edit_turns'}:
    pg.execute('ALTER TABLE '+ident(name)+' ALTER COLUMN entry_seq RESTART WITH '+str(max([r['entry_seq'] for r in records],default=0)+1))
   # Compare every field, not just counts. Double precision preserves SQLite REAL.
   imported=pg.execute(sql.SQL('SELECT {} FROM {}').format(sql.SQL(',').join(map(sql.Identifier,columns)),sql.Identifier(name))).fetchall()
   if Counter(tuple(r) for r in records)!=Counter(tuple(r[c] for c in columns) for r in imported):raise RuntimeError('Data mismatch: '+name)
   print(schema+'.'+name+': '+str(len(records))+' rows verified')
  for statement in foreign:pg.execute(statement)
  for row in original.execute("SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL"):
   if not any(re.search(r'\bON\s+"?'+re.escape(t)+r'"?\s*\(',row['sql'],re.I) for t in ACCOUNT):
    statement=row['sql'].replace('rowid','entry_seq')
    pg.execute(statement);ddl.append(statement+';')
  for row in original.execute("SELECT sql FROM sqlite_master WHERE type='view'"):
   statement=row['sql'].replace('rowid','entry_seq')
   pg.execute(statement);ddl.append(statement+';')
  pg.execute('SET CONSTRAINTS ALL IMMEDIATE')
  Path(config).parent.joinpath('backend/postgres_schema.sql').write_text('-- Service schema; account references use platform. Generated from validated legacy schema.\n'+ '\n'.join(ddl+foreign)+'\n')
  if dry_run:pg.rollback();print('Validation complete; PostgreSQL changes rolled back')
 original.close()

if __name__=='__main__':
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source',required=True);p.add_argument('--config',required=True);p.add_argument('--dry-run',action='store_true');a=p.parse_args();migrate(a.source,a.config,a.dry_run)
