-- Service schema; account references use platform. Generated from validated legacy schema.
CREATE COLLATION IF NOT EXISTS nocase (provider=icu, locale='und-u-ks-level2', deterministic=false);
CREATE TABLE IF NOT EXISTS "domains" (
 domain_id TEXT PRIMARY KEY, host TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "sample_domains" (
 sample_id TEXT NOT NULL,
 domain_id TEXT NOT NULL,
 request_id TEXT,
 kind TEXT NOT NULL CHECK(kind IN ('recommended','manual')),
 description TEXT, recommendation_reason TEXT, topic_relevance TEXT,
 created_at TEXT NOT NULL,
 PRIMARY KEY(sample_id,domain_id),
 CHECK(kind!='manual' OR request_id IS NULL)
);
CREATE TABLE IF NOT EXISTS "llm_requests" (
 request_id TEXT PRIMARY KEY,
 user_id TEXT NOT NULL,
 step TEXT NOT NULL, provider TEXT NOT NULL, model TEXT NOT NULL,
 input_tokens INTEGER, output_tokens INTEGER, total_tokens INTEGER, cached_input_tokens INTEGER,
 started_at TEXT NOT NULL, completed_at TEXT, duration_ms INTEGER
);
CREATE TABLE IF NOT EXISTS "subscriptions" (
 subscription_id TEXT PRIMARY KEY,
 sample_id TEXT NOT NULL,
 user_id TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','paused','cancelled')),
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 UNIQUE(sample_id,user_id)
);
CREATE TABLE IF NOT EXISTS "subscripted_newsletters" (
 newsletter_id TEXT PRIMARY KEY,
 sample_id TEXT NOT NULL,
 coverage_start_date TEXT NOT NULL,
 coverage_end_date TEXT NOT NULL CHECK(coverage_end_date>=coverage_start_date),
 issue_ids TEXT NOT NULL DEFAULT '[]' CHECK((issue_ids IS JSON) AND jsonb_typeof(issue_ids::jsonb)='array'),
 summary TEXT,
 request_id TEXT,
 html_content TEXT NOT NULL,
 created_at TEXT NOT NULL, published_at TEXT,
 UNIQUE(sample_id,coverage_start_date,coverage_end_date)
);
CREATE TABLE IF NOT EXISTS "subscription_history" (
 subscription_id TEXT NOT NULL,
 newsletter_id TEXT NOT NULL,
 created_at TEXT NOT NULL,
 PRIMARY KEY(subscription_id,newsletter_id)
);
CREATE TABLE IF NOT EXISTS "errors" (
 error_id TEXT PRIMARY KEY,
 user_id TEXT NOT NULL,
 step TEXT NOT NULL,
 error_type TEXT NOT NULL,
 message TEXT NOT NULL,
 request_id TEXT,
 created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "subscription_settings" (
 subscription_id TEXT PRIMARY KEY,
 name TEXT NOT NULL CHECK(length(trim(name)) BETWEEN 1 AND 80),
 frequency TEXT NOT NULL CHECK(frequency IN ('daily','weekly','monthly')),
 weekdays TEXT NOT NULL DEFAULT '[]' CHECK((weekdays IS JSON) AND jsonb_typeof(weekdays::jsonb)='array'),
 month_day INTEGER NOT NULL DEFAULT 1 CHECK(month_day BETWEEN 1 AND 31),
 start_date TEXT NOT NULL,
 CHECK(frequency!='weekly' OR jsonb_array_length(weekdays::jsonb)>0)
);
CREATE TABLE IF NOT EXISTS "subject_validation" (
 validation_id TEXT PRIMARY KEY,
 user_id TEXT NOT NULL,
 topic TEXT NOT NULL,
 request_id TEXT,
 candidates_json TEXT NOT NULL CHECK((candidates_json IS JSON) AND jsonb_typeof(candidates_json::jsonb)='array'),
 matches_json TEXT NOT NULL DEFAULT '[]' CHECK((matches_json IS JSON) AND jsonb_typeof(matches_json::jsonb)='array'),
 status TEXT NOT NULL CHECK(status IN ('processing','completed','failed','cancelled')),
 created_at TEXT NOT NULL, completed_at TEXT
);
CREATE TABLE IF NOT EXISTS "sample_queries" (
 query_id TEXT PRIMARY KEY,
 sample_id TEXT NOT NULL,
 request_id TEXT,
 query TEXT NOT NULL CHECK(length(trim(query)) BETWEEN 1 AND 400),
 position INTEGER NOT NULL CHECK(position BETWEEN 1 AND 5),
 created_at TEXT NOT NULL,
 UNIQUE(sample_id,position), UNIQUE(sample_id,query)
);
CREATE TABLE IF NOT EXISTS "sample_articles" (
 sample_id TEXT NOT NULL,
 article_id TEXT NOT NULL,
 request_id TEXT,
 PRIMARY KEY(sample_id,article_id)
);
CREATE TABLE IF NOT EXISTS "sample_issues" (
 issue_id TEXT PRIMARY KEY,
 sample_id TEXT NOT NULL,
 article_id TEXT NOT NULL,
 request_id TEXT,
 rank INTEGER NOT NULL CHECK(rank>0), created_at TEXT NOT NULL,
 UNIQUE(sample_id,article_id), UNIQUE(sample_id,rank));
CREATE TABLE IF NOT EXISTS "sample_runs" (
 run_id TEXT PRIMARY KEY,
 sample_id TEXT NOT NULL,
 user_id TEXT NOT NULL,
 topic TEXT NOT NULL,
 collection_start_date TEXT, collection_end_date TEXT,
 current_step TEXT NOT NULL DEFAULT 'topic_setup',
 status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','running','completed','failed','cancelled')),
 started_at TEXT NOT NULL, completed_at TEXT,
 CHECK(collection_start_date IS NULL OR collection_end_date IS NULL OR collection_end_date>=collection_start_date)
,entry_seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);
CREATE TABLE IF NOT EXISTS "sample_newsletters" (
 sample_id TEXT PRIMARY KEY,
 html_content TEXT, created_at TEXT NOT NULL, saved_at TEXT,
 last_issued_newsletter_id TEXT
, total_summary TEXT, request_id TEXT, search_all_domains INTEGER NOT NULL DEFAULT 0 CHECK(search_all_domains IN (0,1)));
CREATE TABLE IF NOT EXISTS "articles" (
 article_id TEXT PRIMARY KEY,
 domain_id TEXT,
 url TEXT NOT NULL UNIQUE CHECK(length(trim(url))>0), title TEXT NOT NULL,
 published_at TEXT, content TEXT, highlights TEXT,
 image_url TEXT, collected_at TEXT NOT NULL,
 request_id TEXT,
 technical_score DOUBLE PRECISION CHECK(technical_score BETWEEN 0 AND 100),
 organization_score DOUBLE PRECISION CHECK(organization_score BETWEEN 0 AND 100),
 impact_score DOUBLE PRECISION CHECK(impact_score BETWEEN 0 AND 100),
 total_score DOUBLE PRECISION CHECK(total_score BETWEEN 0 AND 100),
 summary TEXT,
 scored_at TEXT, score_version TEXT
, image_storage_path TEXT, newsletter_title TEXT);
CREATE TABLE IF NOT EXISTS "mailing" (
 mailing_id TEXT PRIMARY KEY,
 user_id TEXT,
 request_id TEXT NOT NULL,
 kind TEXT NOT NULL CHECK(kind IN ('sample','subscription')),
 newsletter_id TEXT NOT NULL,
 subject TEXT,
 sender_email TEXT,
 mailing_list TEXT NOT NULL CHECK((mailing_list IS JSON) AND jsonb_typeof(mailing_list::jsonb)='array'),
 results_json TEXT NOT NULL DEFAULT '[]' CHECK((results_json IS JSON) AND jsonb_typeof(results_json::jsonb)='array'),
 status TEXT NOT NULL CHECK(status IN ('processing','completed')),
 created_at TEXT NOT NULL,
 sent_at TEXT,
 completed_at TEXT, subscription_id TEXT,
 UNIQUE(user_id,request_id)
);
CREATE TABLE IF NOT EXISTS "subscription_collection_runs" (
 run_id TEXT PRIMARY KEY,
 sample_id TEXT NOT NULL,
 user_id TEXT NOT NULL,
 collection_date TEXT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('running','completed','failed','cancelled')),
 attempt INTEGER NOT NULL DEFAULT 1,
 attempt_token TEXT NOT NULL,
 configuration_json TEXT NOT NULL,
 request_id TEXT,
 search_results INTEGER NOT NULL DEFAULT 0,
 url_duplicates INTEGER NOT NULL DEFAULT 0,
 invalid_results INTEGER NOT NULL DEFAULT 0,
 history_url_excluded INTEGER NOT NULL DEFAULT 0,
 candidate_count INTEGER NOT NULL DEFAULT 0,
 retained_count INTEGER NOT NULL DEFAULT 0,
 saved_count INTEGER NOT NULL DEFAULT 0,
 started_at TEXT NOT NULL,
 completed_at TEXT,
 UNIQUE(sample_id,collection_date)
);
CREATE TABLE IF NOT EXISTS "subscripted_articles" (
            sample_id TEXT NOT NULL,
            article_id TEXT NOT NULL,
            request_id TEXT,
            run_id TEXT,
            collected_at TEXT NOT NULL, PRIMARY KEY(sample_id,article_id));
CREATE TABLE IF NOT EXISTS "subscripted_issues" (
            issue_id TEXT PRIMARY KEY,
            subscription_id TEXT NOT NULL,
            article_id TEXT NOT NULL,
            request_id TEXT,
            summary TEXT,rank INTEGER NOT NULL CHECK(rank>0),created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "subscription_members" (
        member_id TEXT PRIMARY KEY,
        subscription_id TEXT NOT NULL,
        member_type TEXT NOT NULL CHECK(member_type IN ('internal','external')),
        user_id TEXT,
        email_address TEXT COLLATE NOCASE,
        created_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','paused')),
        CHECK((member_type='internal' AND user_id IS NOT NULL AND length(trim(user_id))>0 AND email_address IS NULL)
           OR (member_type='external' AND user_id IS NULL AND email_address IS NOT NULL AND length(trim(email_address))>0))
    );
CREATE TABLE IF NOT EXISTS "subscription_publication_jobs" (
 job_id TEXT PRIMARY KEY,
 subscription_id TEXT NOT NULL,
 scheduled_date TEXT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('running','completed','skipped','failed','review')),
 attempt INTEGER NOT NULL DEFAULT 1,
 attempt_token TEXT NOT NULL,
 newsletter_id TEXT,
 started_at TEXT NOT NULL,
 completed_at TEXT,
 UNIQUE(subscription_id,scheduled_date)
);
CREATE TABLE IF NOT EXISTS "llm_pricing" (
            provider TEXT NOT NULL, model TEXT NOT NULL,
            input_rate DOUBLE PRECISION NOT NULL CHECK(input_rate>=0),
            cached_rate DOUBLE PRECISION NOT NULL CHECK(cached_rate>=0),
            output_rate DOUBLE PRECISION NOT NULL CHECK(output_rate>=0),
            updated_at TEXT NOT NULL, PRIMARY KEY(provider,model));
CREATE TABLE IF NOT EXISTS "subscription_llm_requests" (
            request_id TEXT PRIMARY KEY,
            sample_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "exa_search_usage" (
            usage_id TEXT PRIMARY KEY,
            user_id TEXT,
            sample_id TEXT,
            kind TEXT NOT NULL CHECK(kind IN ('sample','subscription')),
            run_id TEXT,
            result_count INTEGER NOT NULL CHECK(result_count>=0),
            created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "subscription_feedback" (
            feedback_id TEXT PRIMARY KEY,
            subscription_id TEXT,
            sample_id TEXT,
            user_id TEXT,
            requester_name TEXT NOT NULL,requester_email TEXT NOT NULL,
            subscription_name TEXT NOT NULL,topic TEXT NOT NULL,
            conditions_json TEXT NOT NULL CHECK((conditions_json IS JSON) AND jsonb_typeof(conditions_json::jsonb)='object'),content TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','completed','held')),
            revision INTEGER NOT NULL DEFAULT 0,
            response TEXT,handled_by TEXT,
            created_at TEXT NOT NULL,handled_at TEXT,
            notifications_json TEXT NOT NULL DEFAULT '[]' CHECK((notifications_json IS JSON) AND jsonb_typeof(notifications_json::jsonb)='array'));
CREATE INDEX sample_domains_request ON sample_domains(request_id);
CREATE INDEX llm_requests_user_step ON llm_requests(user_id,step,started_at);
CREATE INDEX subscriptions_reference ON subscriptions(sample_id,status);
CREATE INDEX subscripted_newsletters_sample ON subscripted_newsletters(sample_id,published_at);
CREATE INDEX subscripted_newsletters_request ON subscripted_newsletters(request_id);
CREATE INDEX subscription_history_newsletter ON subscription_history(newsletter_id);
CREATE INDEX errors_user_step ON errors(user_id,step,created_at);
CREATE INDEX errors_request ON errors(request_id);
CREATE INDEX subject_validation_user ON subject_validation(user_id,created_at);
CREATE INDEX subject_validation_request ON subject_validation(request_id);
CREATE INDEX sample_queries_request ON sample_queries(request_id);
CREATE INDEX sample_articles_article ON sample_articles(article_id);
CREATE INDEX sample_issues_rank ON sample_issues(sample_id,rank);
CREATE INDEX sample_runs_sample ON sample_runs(sample_id,started_at);
CREATE INDEX sample_runs_user ON sample_runs(user_id,started_at);
CREATE INDEX articles_published ON articles(published_at);
CREATE INDEX articles_request ON articles(request_id);
CREATE INDEX mailing_newsletter ON mailing(kind,newsletter_id,created_at);
CREATE INDEX mailing_user ON mailing(user_id,created_at);
CREATE UNIQUE INDEX subscription_collection_running ON subscription_collection_runs(sample_id) WHERE status='running';
CREATE INDEX subscription_collection_date ON subscription_collection_runs(collection_date,status);
CREATE INDEX subscripted_articles_article ON subscripted_articles(article_id);
CREATE INDEX subscripted_articles_collected ON subscripted_articles(sample_id,collected_at);
CREATE INDEX subscripted_issues_subscription ON subscripted_issues(subscription_id,created_at);
CREATE INDEX subscripted_issues_article ON subscripted_issues(article_id);
CREATE INDEX subscripted_issues_request ON subscripted_issues(request_id);
CREATE UNIQUE INDEX subscription_member_user ON subscription_members(subscription_id,user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX subscription_member_email ON subscription_members(subscription_id,email_address) WHERE email_address IS NOT NULL;
CREATE INDEX subscription_member_lookup ON subscription_members(user_id,subscription_id);
CREATE UNIQUE INDEX mailing_subscription_edition ON mailing(subscription_id,newsletter_id) WHERE subscription_id IS NOT NULL;
CREATE INDEX subscription_llm_sample ON subscription_llm_requests(sample_id);
CREATE INDEX exa_usage_time ON exa_search_usage(created_at);
CREATE INDEX exa_usage_run ON exa_search_usage(run_id);
CREATE INDEX feedback_status_created ON subscription_feedback(status,created_at);
CREATE VIEW sample_details AS
SELECT n.*,r.run_id,r.user_id,r.topic,r.collection_start_date,r.collection_end_date,
       CASE WHEN r.status='completed' THEN 'completed' ELSE 'draft' END AS status,
       r.status AS run_status,r.current_step,r.started_at,r.completed_at
FROM sample_newsletters n JOIN sample_runs r ON r.run_id=(
 SELECT x.run_id FROM sample_runs x WHERE x.sample_id=n.sample_id ORDER BY x.entry_seq DESC LIMIT 1);
ALTER TABLE "sample_domains" ADD CONSTRAINT "sample_domains_fk_0" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_domains" ADD CONSTRAINT "sample_domains_fk_1" FOREIGN KEY ("domain_id") REFERENCES "wianews"."domains" ("domain_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_domains" ADD CONSTRAINT "sample_domains_fk_2" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "llm_requests" ADD CONSTRAINT "llm_requests_fk_0" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_fk_0" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_fk_1" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscripted_newsletters" ADD CONSTRAINT "subscripted_newsletters_fk_0" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscripted_newsletters" ADD CONSTRAINT "subscripted_newsletters_fk_1" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_history" ADD CONSTRAINT "subscription_history_fk_0" FOREIGN KEY ("newsletter_id") REFERENCES "wianews"."subscripted_newsletters" ("newsletter_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_history" ADD CONSTRAINT "subscription_history_fk_1" FOREIGN KEY ("subscription_id") REFERENCES "wianews"."subscriptions" ("subscription_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "errors" ADD CONSTRAINT "errors_fk_0" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "errors" ADD CONSTRAINT "errors_fk_1" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_settings" ADD CONSTRAINT "subscription_settings_fk_0" FOREIGN KEY ("subscription_id") REFERENCES "wianews"."subscriptions" ("subscription_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subject_validation" ADD CONSTRAINT "subject_validation_fk_0" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subject_validation" ADD CONSTRAINT "subject_validation_fk_1" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_queries" ADD CONSTRAINT "sample_queries_fk_0" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_queries" ADD CONSTRAINT "sample_queries_fk_1" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_articles" ADD CONSTRAINT "sample_articles_fk_0" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_articles" ADD CONSTRAINT "sample_articles_fk_1" FOREIGN KEY ("article_id") REFERENCES "wianews"."articles" ("article_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_articles" ADD CONSTRAINT "sample_articles_fk_2" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_issues" ADD CONSTRAINT "sample_issues_fk_0" FOREIGN KEY ("sample_id","article_id") REFERENCES "wianews"."sample_articles" ("sample_id","article_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_issues" ADD CONSTRAINT "sample_issues_fk_1" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_issues" ADD CONSTRAINT "sample_issues_fk_2" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_runs" ADD CONSTRAINT "sample_runs_fk_0" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_runs" ADD CONSTRAINT "sample_runs_fk_1" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_newsletters" ADD CONSTRAINT "sample_newsletters_fk_0" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sample_newsletters" ADD CONSTRAINT "sample_newsletters_fk_1" FOREIGN KEY ("last_issued_newsletter_id") REFERENCES "wianews"."subscripted_newsletters" ("newsletter_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "articles" ADD CONSTRAINT "articles_fk_0" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "articles" ADD CONSTRAINT "articles_fk_1" FOREIGN KEY ("domain_id") REFERENCES "wianews"."domains" ("domain_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mailing" ADD CONSTRAINT "mailing_fk_0" FOREIGN KEY ("subscription_id") REFERENCES "wianews"."subscriptions" ("subscription_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mailing" ADD CONSTRAINT "mailing_fk_1" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_collection_runs" ADD CONSTRAINT "subscription_collection_runs_fk_0" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_collection_runs" ADD CONSTRAINT "subscription_collection_runs_fk_1" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_collection_runs" ADD CONSTRAINT "subscription_collection_runs_fk_2" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscripted_articles" ADD CONSTRAINT "subscripted_articles_fk_0" FOREIGN KEY ("run_id") REFERENCES "wianews"."subscription_collection_runs" ("run_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscripted_articles" ADD CONSTRAINT "subscripted_articles_fk_1" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscripted_articles" ADD CONSTRAINT "subscripted_articles_fk_2" FOREIGN KEY ("article_id") REFERENCES "wianews"."articles" ("article_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscripted_articles" ADD CONSTRAINT "subscripted_articles_fk_3" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscripted_issues" ADD CONSTRAINT "subscripted_issues_fk_0" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscripted_issues" ADD CONSTRAINT "subscripted_issues_fk_1" FOREIGN KEY ("article_id") REFERENCES "wianews"."articles" ("article_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscripted_issues" ADD CONSTRAINT "subscripted_issues_fk_2" FOREIGN KEY ("subscription_id") REFERENCES "wianews"."subscriptions" ("subscription_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_members" ADD CONSTRAINT "subscription_members_fk_0" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_members" ADD CONSTRAINT "subscription_members_fk_1" FOREIGN KEY ("subscription_id") REFERENCES "wianews"."subscriptions" ("subscription_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_publication_jobs" ADD CONSTRAINT "subscription_publication_jobs_fk_0" FOREIGN KEY ("newsletter_id") REFERENCES "wianews"."subscripted_newsletters" ("newsletter_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_publication_jobs" ADD CONSTRAINT "subscription_publication_jobs_fk_1" FOREIGN KEY ("subscription_id") REFERENCES "wianews"."subscriptions" ("subscription_id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_llm_requests" ADD CONSTRAINT "subscription_llm_requests_fk_0" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_llm_requests" ADD CONSTRAINT "subscription_llm_requests_fk_1" FOREIGN KEY ("request_id") REFERENCES "wianews"."llm_requests" ("request_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "exa_search_usage" ADD CONSTRAINT "exa_search_usage_fk_0" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "exa_search_usage" ADD CONSTRAINT "exa_search_usage_fk_1" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_feedback" ADD CONSTRAINT "subscription_feedback_fk_0" FOREIGN KEY ("handled_by") REFERENCES "platform"."users" ("user_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_feedback" ADD CONSTRAINT "subscription_feedback_fk_1" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_feedback" ADD CONSTRAINT "subscription_feedback_fk_2" FOREIGN KEY ("sample_id") REFERENCES "wianews"."sample_newsletters" ("sample_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscription_feedback" ADD CONSTRAINT "subscription_feedback_fk_3" FOREIGN KEY ("subscription_id") REFERENCES "wianews"."subscriptions" ("subscription_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
