import React, { useEffect, useRef, useState } from 'react';
import { UserRound, Layers3, Users, LogOut, ChevronRight, Search, X, Loader2, Check, Pencil, Trash2, KeyRound } from 'lucide-react';
import { authRequest, postAuth } from './authApi';
import NameAutocomplete from './NameAutocomplete';
import { sortAccounts } from './accountSort';

const emptyForm=()=>({employee_id:'',full_name:'',email:'',team_name:'',role_name:'',is_admin:false});
const userForm=u=>({employee_id:u.employee_id,full_name:u.full_name,email:u.email,team_name:u.team_name,role_name:u.role_name,is_admin:!!u.is_admin});
function AccountFields({value,onChange,options,lockAdmin=false,compact=false}) {
  return <>
    <label>사번<input required pattern={compact?"[0-9]{1,7}":"[A-Za-z0-9._-]+"} inputMode={compact?"numeric":undefined} maxLength={compact?7:40} title={compact?"숫자 7자리 이하":undefined} value={value.employee_id} onChange={e=>onChange({...value,employee_id:e.target.value})}/></label>
    <label>이름<input required maxLength={80} value={value.full_name} onChange={e=>onChange({...value,full_name:e.target.value})}/></label>
    <label>이메일<input type="email" maxLength={254} value={value.email} onChange={e=>onChange({...value,email:e.target.value})}/></label>
    <NameAutocomplete label="소속 팀" value={value.team_name} onChange={team_name=>onChange({...value,team_name})} options={options.teams}/>
    <NameAutocomplete label="직급" value={value.role_name} onChange={role_name=>onChange({...value,role_name})} options={options.roles}/>
    <label className="account-admin-field"><span>{compact?'관리자':'관리자 권한'}</span><span className="account-admin-toggle" title="관리자 계정으로 등록"><input type="checkbox" disabled={lockAdmin} checked={value.is_admin} onChange={e=>onChange({...value,is_admin:e.target.checked})}/>{!compact&&'관리자 계정으로 등록'}</span><small>{lockAdmin?'본인의 관리자 권한은 해제할 수 없습니다.':'관리자는 계정 관리 메뉴만 사용할 수 있습니다.'}</small></label>
  </>;
}
function AccountDialog({title,busy,onClose,children,className=''}) {
  const ref=useRef(null);
  useEffect(()=>{const dialog=ref.current;dialog.showModal();return()=>dialog.close();},[]);
  return <dialog ref={ref} className={`account-dialog ${className}`} aria-label={title} onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="section-title"><h2>{title}</h2><button className="icon-button" aria-label="팝업 닫기" disabled={busy} onClick={onClose}><X size={20}/></button></div>{children}</dialog>;
}
export default function AccountManagement({user,onLogout}) {
  const [users,setUsers]=useState([]);const [options,setOptions]=useState({teams:[],roles:[]});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [message,setMessage]=useState('');const [query,setQuery]=useState('');const [form,setForm]=useState(emptyForm);const [formVersion,setFormVersion]=useState(0);const [busy,setBusy]=useState(false);
  const [editing,setEditing]=useState(null);const [deleting,setDeleting]=useState(null);const [resetting,setResetting]=useState(null);const [dialogError,setDialogError]=useState('');
  async function load(){setLoading(true);setError('');try{const [rows,opts]=await Promise.all([authRequest('/admin/users'),authRequest('/admin/options')]);setUsers(rows);setOptions(opts);}catch(err){setError(err.message);}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  function resetForm(){setForm(emptyForm());setFormVersion(v=>v+1);setError('');setMessage('');}
  function updateOptions(saved){setOptions(current=>({teams:current.teams.some(t=>t.team_id===saved.team_id)?current.teams:[...current.teams,{team_id:saved.team_id,name:saved.team_name}],roles:current.roles.some(r=>r.role_id===saved.role_id)?current.roles:[...current.roles,{role_id:saved.role_id,name:saved.role_name}]}));}
  async function create(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{const created=await postAuth('/admin/users',form);setUsers(rows=>[created,...rows]);updateOptions(created);resetForm();setMessage(`${created.full_name} (${created.employee_id}) 계정을 등록했습니다. 초기 비밀번호는 wia1234! 입니다.`);}catch(err){setError(err.message);}finally{setBusy(false);}}
  async function saveEdit(e){e.preventDefault();setBusy(true);setDialogError('');try{const saved=await authRequest(`/admin/users/${editing.id}`,{method:'PUT',body:JSON.stringify(editing.values)});setUsers(rows=>rows.map(u=>u.user_id===saved.user_id?saved:u));updateOptions(saved);setEditing(null);setMessage(`${saved.full_name} 계정을 수정했습니다.`);}catch(err){setDialogError(err.message);}finally{setBusy(false);}}
  async function remove(){setBusy(true);setDialogError('');try{await authRequest(`/admin/users/${deleting.user_id}`,{method:'DELETE'});setUsers(rows=>rows.filter(u=>u.user_id!==deleting.user_id));setMessage(`${deleting.full_name} 계정을 삭제했습니다.`);setDeleting(null);}catch(err){setDialogError(err.message);}finally{setBusy(false);}}
  async function resetPassword(){setBusy(true);setDialogError('');try{const saved=await postAuth(`/admin/users/${resetting.user_id}/reset-password`);setUsers(rows=>rows.map(u=>u.user_id===saved.user_id?saved:u));setResetting(null);setMessage(`${saved.full_name} 계정의 비밀번호를 wia1234! 로 초기화했습니다. 다음 로그인 시 변경이 필요합니다.`);if(saved.user_id===user.user_id)window.dispatchEvent(new Event('wianews-session-expired'));}catch(err){setDialogError(err.message);}finally{setBusy(false);}}
  const visible=sortAccounts(users).filter(u=>`${u.employee_id} ${u.full_name} ${u.email} ${u.team_name} ${u.role_name}`.toLowerCase().includes(query.toLowerCase()));
  const date=value=>value?new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-icon"><Layers3 size={24}/></span><div>WiaNews<small>ADMIN WORKSPACE</small></div></div><div className="workspace-label">ADMINISTRATION</div><nav><button className="active"><Users size={17}/>계정 관리<ChevronRight size={14}/></button></nav><div className="side-bottom"><div className="profile"><span aria-hidden="true"><UserRound size={20}/></span><div>{user.full_name}<small>관리자</small></div></div><button className="sidebar-logout" onClick={onLogout}><LogOut size={16}/>로그아웃</button></div></aside>
    <div className="main-shell"><header className="topbar"><div>Workspace<ChevronRight size={13}/><strong>계정 관리</strong></div><span className="demo-badge">관리자</span></header><main className="accounts-page"><div className="page-heading"><div><div className="eyebrow">ACCOUNT MANAGEMENT</div><h1>계정 관리</h1><p>사용자 계정을 추가하고 소속 팀·직급과 관리자 권한을 관리하세요.</p></div></div>
      {message&&<div className="account-success" role="status"><Check size={17}/>{message}</div>}
      {error&&<div className="auth-error" role="alert">{error}<button className="auth-text-button" disabled={busy||loading} onClick={load}>다시 불러오기</button></div>}
      <section className="panel account-editor"><div className="section-title"><div><h2>계정 추가</h2><p>초기 비밀번호는 wia1234! 이며, 첫 로그인 후 반드시 변경해야 합니다.</p></div></div><form onSubmit={create}><fieldset disabled={busy||loading} className="account-fields">
        <AccountFields compact key={formVersion} value={form} onChange={setForm} options={options}/>
        <div className="account-form-actions"><button type="button" className="button" onClick={resetForm}>초기화</button><button type="submit" className="button primary">{busy&&!editing&&!deleting&&!resetting&&<Loader2 size={15} className="spin"/>}등록</button></div>
      </fieldset></form></section>
      <section className="panel account-list"><div className="section-title"><h2>전체 계정 <span className="count">{users.length}</span></h2><label className="account-search"><Search size={16}/><input aria-label="계정 검색" placeholder="사번, 이름, 팀, 직급 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
      {loading?<div className="empty"><Loader2 className="spin"/>계정을 불러오고 있습니다.</div>:<div className="account-table-wrap"><table><thead><tr><th>사용자 / 사번</th><th>소속 팀</th><th>직급</th><th>권한</th><th>이메일</th><th>비밀번호 상태</th><th>최근 로그인</th><th>생성일</th><th>관리</th></tr></thead><tbody>{visible.map(u=><tr key={u.user_id}><td><strong>{u.full_name}</strong><small>{u.employee_id}</small></td><td>{u.team_name}</td><td>{u.role_name}</td><td><span className={`role-pill ${u.is_admin?'admin':'member'}`}>{u.is_admin?'관리자':'일반 사용자'}</span></td><td>{u.email||'—'}</td><td><span className={`password-state ${u.must_change_password?'pending':''}`}>{u.must_change_password?'변경 필요':'설정 완료'}</span></td><td>{date(u.last_login_at)}</td><td>{date(u.created_at)}</td><td><div className="account-row-actions"><button className="icon-button" title="계정 편집" aria-label={`${u.employee_id} 계정 편집`} disabled={busy} onClick={()=>{setDialogError('');setEditing({id:u.user_id,values:userForm(u)});}}><Pencil size={17}/></button><button className="icon-button reset-password" title="비밀번호 초기화" aria-label={`${u.employee_id} 비밀번호 초기화`} disabled={busy} onClick={()=>{setDialogError('');setResetting(u);}}><KeyRound size={17}/></button><button className="icon-button delete-account" title={u.user_id===user.user_id?'본인 계정은 삭제할 수 없습니다.':'계정 삭제'} aria-label={`${u.employee_id} 계정 삭제`} disabled={busy||u.user_id===user.user_id} onClick={()=>{setDialogError('');setDeleting(u);}}><Trash2 size={17}/></button></div></td></tr>)}</tbody></table>{!visible.length&&<div className="empty">검색 결과가 없습니다.</div>}</div>}</section>
    </main></div>
    {editing&&<AccountDialog title="계정 편집" busy={busy} onClose={()=>setEditing(null)}><form onSubmit={saveEdit}><fieldset className="account-fields" disabled={busy}><AccountFields value={editing.values} onChange={values=>setEditing(current=>({...current,values}))} options={options} lockAdmin={editing.id===user.user_id}/>{dialogError&&<p className="auth-error account-dialog-error" role="alert">{dialogError}</p>}<div className="account-form-actions"><button type="button" className="button" onClick={()=>setEditing(null)}>취소</button><button className="button primary" type="submit">{busy&&<Loader2 size={15} className="spin"/>}저장</button></div></fieldset></form></AccountDialog>}
    {resetting&&<AccountDialog title="비밀번호 초기화" className="delete-dialog" busy={busy} onClose={()=>setResetting(null)}><p><strong>{resetting.full_name} ({resetting.employee_id})</strong> 계정의 비밀번호를 초기화하시겠습니까?</p><p>초기 비밀번호는 <strong>wia1234!</strong> 입니다.<br/>기존 로그인은 종료되며 다음 로그인 시 비밀번호를 반드시 변경해야 합니다.</p>{resetting.user_id===user.user_id&&<p>본인 계정을 초기화하면 현재 화면에서도 로그아웃됩니다.</p>}{dialogError&&<p className="auth-error" role="alert">{dialogError}</p>}<div className="account-form-actions"><button className="button" disabled={busy} onClick={()=>setResetting(null)}>취소</button><button className="button primary" disabled={busy} onClick={resetPassword}>{busy&&<Loader2 size={15} className="spin"/>}초기화</button></div></AccountDialog>}
    {deleting&&<AccountDialog title="계정 삭제" className="delete-dialog" busy={busy} onClose={()=>setDeleting(null)}><p><strong>{deleting.full_name} ({deleting.employee_id})</strong> 계정을 삭제하시겠습니까?</p><p>삭제하면 해당 계정으로 로그인할 수 없습니다.</p>{dialogError&&<p className="auth-error" role="alert">{dialogError}</p>}<div className="account-form-actions"><button className="button" disabled={busy} onClick={()=>setDeleting(null)}>취소</button><button className="button danger" disabled={busy} onClick={remove}>{busy&&<Loader2 size={15} className="spin"/>}삭제</button></div></AccountDialog>}
  </div>;
}
