import React,{useEffect,useRef,useState} from 'react';
import {Search,ExternalLink,RefreshCw,Loader2,X,Newspaper} from 'lucide-react';
import {authRequest} from './authApi';
const title=r=>r.newsletter_title||r.title;
const score=n=>n==null?'평가 대기':`${Number(n).toLocaleString('ko-KR',{maximumFractionDigits:1})}점`;
const day=s=>s?s.slice(0,10):'—';
function safeUrl(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function Reference({url}){const href=safeUrl(url);return href?<a className="admin-news-reference" href={href} target="_blank" rel="noopener noreferrer">Reference<ExternalLink size={14}/></a>:<span>—</span>;}
function Preview({id,onClose}){
 const ref=useRef(null);const [data,setData]=useState(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>previous?.focus();},[]);
 useEffect(()=>{const c=new AbortController();setData(null);setError('');authRequest(`/admin/news/${id}`,{signal:c.signal}).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[id,attempt]);
 return <dialog ref={ref} className="admin-news-preview" aria-labelledby="admin-news-preview-title" onCancel={e=>{e.preventDefault();onClose();}}><header className="admin-panel-title"><h2 id="admin-news-preview-title">뉴스 미리보기</h2><button className="icon-button" aria-label="뉴스 미리보기 닫기" onClick={onClose}><X size={20}/></button></header>{error?<div className="auth-error" role="alert">{error}<button className="button" onClick={()=>setAttempt(v=>v+1)}>다시 불러오기</button></div>:data?<><h3>{title(data)}</h3><div className="admin-news-meta"><span>{data.host}</span><time>{day(data.published_at)}</time><span className="admin-news-score">{score(data.total_score)}</span><Reference url={data.url}/></div>{safeUrl(data.image_url)&&<a href={safeUrl(data.image_url)} target="_blank" rel="noopener noreferrer" title="원본 이미지 보기"><img key={data.image_url} className="admin-news-image" src={safeUrl(data.image_url)} alt={title(data)} referrerPolicy="no-referrer" onError={e=>{e.currentTarget.hidden=true;}}/></a>}<div className="admin-news-summary"><h4>{data.summary?'기사 요약':'수집된 기사 본문'}</h4><p>{data.summary||data.content||'저장된 기사 내용이 없습니다.'}</p></div></>:<div className="empty" role="status"><Loader2 className="spin"/>기사를 불러오는 중입니다.</div>}</dialog>;
}
export default function AdminNews(){
 const [page,setPage]=useState(1),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0),[preview,setPreview]=useState(null);const table=useRef(null);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');authRequest(`/admin/news?page=${page}`,{signal:c.signal}).then(d=>{if(!c.signal.aborted){setData(d);if(table.current)table.current.scrollTop=0;}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[page,revision]);
 return <main className="admin-page"><div className="page-heading"><div><div className="eyebrow">COLLECTED NEWS</div><h1>뉴스 관리</h1><p>샘플과 구독에서 수집한 모든 뉴스를 확인하세요.</p></div><button className="button" disabled={loading} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={16}/>새로고침</button></div><section className="admin-panel admin-news-panel"><div className="admin-panel-title"><h2>수집된 뉴스 <span className="count">{data?.total?.toLocaleString('ko-KR')||0}</span></h2><small>수집 최신순 · 페이지당 20개</small></div>{error?<p className="auth-error" role="alert">{error}</p>:loading?<div className="empty" role="status"><Loader2 className="spin"/>뉴스를 불러오는 중입니다.</div>:<div ref={table} className="admin-table-scroll admin-news-table"><table><thead><tr><th scope="col">뉴스 제목</th><th scope="col">발행일</th><th scope="col">평가 점수</th><th scope="col">미리보기</th><th scope="col">Reference</th></tr></thead><tbody>{data?.items.map(r=><tr key={r.article_id}><td><strong>{title(r)}</strong></td><td><time>{day(r.published_at)}</time></td><td><span className={`admin-news-score ${r.total_score==null?'pending':''}`}>{score(r.total_score)}</span></td><td><button className="icon-button" title="뉴스 미리보기" aria-label={`${title(r)} 미리보기`} onClick={()=>setPreview(r.article_id)}><Search size={18}/></button></td><td><Reference url={r.url}/></td></tr>)}</tbody></table>{!data?.items.length&&<div className="empty"><Newspaper size={30}/>수집된 뉴스가 없습니다.</div>}</div>}<div className="admin-pagination"><span>{data?.total?`${(page-1)*20+1}–${Math.min(page*20,data.total)} / ${data.total.toLocaleString('ko-KR')}건`:'0건'} · {page} 페이지</span><button className="button" disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>이전</button><button className="button" disabled={loading||!!error||!data?.has_next} onClick={()=>setPage(p=>p+1)}>다음</button></div></section>{preview&&<Preview id={preview} onClose={()=>setPreview(null)}/>}</main>;
}
