import React,{useEffect,useRef,useState} from 'react';
import {RefreshCw,MessageSquareText,Check,Pause,Mail,Loader2,X} from 'lucide-react';
import {authRequest,postAuth} from './authApi';
import './feedback.css';
import FeedbackApply from './FeedbackApply';
const names={pending:'검토 대기',held:'보류',completed:'반영'};
const mails={processing:'메일 발송 중',sent:'결과 메일 발송 완료',failed:'메일 발송 실패',unknown:'메일 발송 결과 확인 필요'};
const stamp=s=>new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'});
function Decision({item,status,onClose,onDone}){
 const ref=useRef(null),request=useRef(null);const [response,setResponse]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>previous?.focus();},[]);
 async function submit(e){e.preventDefault();if(busy)return;setBusy(true);setError('');if(!request.current||request.current.response!==response.trim())request.current={request_id:crypto.randomUUID(),revision:item.revision,status,response:response.trim()};
 try{const result=await postAuth(`/admin/feedback/${item.feedback_id}/decision`,request.current);onDone(result);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <dialog ref={ref} className="feedback-dialog feedback-decision" aria-labelledby="feedback-decision-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="feedback-dialog-head"><div><h2 id="feedback-decision-title">피드백 {names[status]}</h2><p>{item.subscription_name}</p></div><button className="icon-button" disabled={busy} onClick={onClose} aria-label="처리 창 닫기"><X size={20}/></button></div><p className="feedback-recipient"><Mail size={16}/>{item.requester_name} · {item.requester_email}</p><form onSubmit={submit}><label className="feedback-input">{status==='completed'?'처리 내용':'보류 이유 및 안내'}<textarea autoFocus required maxLength={3000} rows={6} value={response} disabled={busy} onChange={e=>setResponse(e.target.value)} placeholder={status==='completed'?'실제 적용한 쿼리·도메인 변경 내용을 적어 주세요.':'보류 이유와 추가 검토 사항을 안내해 주세요.'}/></label><p className="admin-note">보류 이유를 저장하고 위 이메일로 안내합니다. 수집 조건은 변경되지 않습니다.</p>{error&&<p className="auth-error" role="alert">{error}</p>}<footer className="feedback-actions"><button type="button" className="button" disabled={busy} onClick={onClose}>취소</button><button className="button primary" disabled={busy||!response.trim()}>{busy&&<Loader2 size={16} className="spin"/>}{busy?'저장 및 발송 중…':`${names[status]} 및 메일 발송`}</button></footer></form></dialog>;
}
export default function AdminFeedback(){
 const [filter,setFilter]=useState('all'),[data,setData]=useState(null),[offset,setOffset]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[revision,setRevision]=useState(0),[decision,setDecision]=useState(null),[busy,setBusy]=useState(null);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');authRequest(`/admin/feedback?status=${filter}&offset=${offset}`,{signal:c.signal}).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[filter,offset,revision]);
 function completed(result){const event=result.notifications.at(-1);setMessage(`피드백을 ${names[result.status]}로 저장했습니다. ${mails[event?.mail_status]||''}`);setDecision(null);setRevision(v=>v+1);}
 async function retry(item){setBusy(item.feedback_id);setError('');try{const result=await postAuth(`/admin/feedback/${item.feedback_id}/retry-email`,{event_id:item.notifications.at(-1).id});completed(result);}catch(e){setError(e.message);}finally{setBusy(null);}}
 return <main className="admin-page"><div className="page-heading"><div><div className="eyebrow">SUBSCRIPTION FEEDBACK</div><h1>피드백 관리</h1><p>구독자의 수집 조건 변경 요청을 검토하고 처리 결과를 안내하세요.</p></div><button className="button" disabled={loading||!!busy} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={16}/>새로고침</button></div><div className="admin-tabs feedback-tabs">{[['all','전체'],...Object.entries(names)].map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>{setFilter(key);setOffset(0);}}>{label}<span>{key==='all'?Object.values(data?.counts||{}).reduce((a,b)=>a+b,0):data?.counts[key]||0}</span></button>)}</div>{message&&<p className="account-success" role="status">{message}</p>}{error&&<p className="auth-error" role="alert">{error}</p>}
 {loading?<div className="empty"><Loader2 className="spin"/>피드백을 불러오는 중입니다.</div>:data&&<><div className="feedback-grid">{data.items.map(item=>{const last=item.notifications.at(-1);return <article className="feedback-card" key={item.feedback_id}><div className="feedback-card-top"><span className={`feedback-badge ${item.status}`}>{names[item.status]}</span><time>{stamp(item.created_at)}</time></div><h2>{item.subscription_name}</h2><p className="feedback-topic">{item.topic}</p><div className="feedback-author"><MessageSquareText size={17}/><span><strong>{item.requester_name}</strong><small>{item.requester_email}</small></span></div><p className="feedback-content">{item.content}</p><details className="feedback-current"><summary>요청 당시 수집 조건</summary><p><b>쿼리</b><br/>{item.conditions.queries.join(' / ')||'없음'}</p><p><b>도메인</b><br/>{item.conditions.search_all_domains?'전체 도메인 검색':item.conditions.domains.join(', ')||'없음'}</p></details>{item.notifications.length>0&&<div className="feedback-responses">{item.notifications.map(n=><div key={n.id}><div><b>{names[n.status]}</b><small>{stamp(n.handled_at)}</small></div><p>{n.response}</p><span className={`feedback-mail ${n.mail_status}`}><Mail size={13}/>{mails[n.mail_status]}</span></div>)}</div>}
 <footer className="feedback-card-actions">{last?.mail_status==='failed'&&<button className="button" disabled={!!busy} onClick={()=>retry(item)}><Mail size={15}/>메일 재발송</button>}{item.status!=='completed'&&<><button className="button" disabled={!!busy||last?.mail_status==='processing'} onClick={()=>setDecision({item,status:'held'})}><Pause size={15}/>보류</button><button className="button primary" disabled={!!busy||last?.mail_status==='processing'} onClick={()=>setDecision({item,status:'completed'})}><Check size={15}/>반영</button></>}</footer></article>;})}</div>{!data.items.length&&<div className="empty"><MessageSquareText size={30}/>해당 상태의 피드백이 없습니다.</div>}<div className="admin-pagination"><span>총 {data.total}건 · {offset/30+1} 페이지</span><button className="button" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-30))}>이전</button><button className="button" disabled={offset+30>=data.total} onClick={()=>setOffset(v=>v+30)}>다음</button></div></>}{decision&&(decision.status==='completed'?<FeedbackApply item={decision.item} onClose={()=>setDecision(null)} onDone={completed}/>:<Decision {...decision} onClose={()=>setDecision(null)} onDone={completed}/>)}</main>;
}
