import React, {useEffect,useRef,useState} from 'react';
import {RefreshCw,Search,Plus,Trash2,Users,CalendarDays,SlidersHorizontal,Loader2,X,Eye,Radio} from 'lucide-react';
import {authRequest} from './authApi';
import RecipientSearchDialog from './RecipientSearchDialog';

const days=['일','월','화','수','목','금','토'];
const timestamp=s=>s?new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'—';
const schedule=r=>r.frequency==='daily'?'매일':r.frequency==='weekly'?'매주 '+(typeof r.weekdays==='string'?JSON.parse(r.weekdays):r.weekdays).map(d=>days[d]).join('·')+'요일':`매월 ${r.monthDay||r.month_day}일`;
const identity=m=>m.member_type==='external'?`external:${m.email_address||m.email}`:m.user_id;
const bodyMember=m=>({member_type:m.member_type||'internal',user_id:m.member_type==='external'?null:m.user_id,email_address:m.member_type==='external'?(m.email_address||m.email):null,status:m.status||'active'});
const formFrom=d=>({name:d.name,frequency:d.frequency,weekdays:d.weekdays,month_day:d.monthDay,start_date:d.startDate||d.created_at.slice(0,10),search_all_domains:d.search_all_domains,queries:[...d.queries],domains:[...d.domains]});
function Preview({sid,id,onClose}){
 const ref=useRef(null);const [data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>previous?.focus();},[]);
 useEffect(()=>{const controller=new AbortController();authRequest(`/admin/subscriptions/${sid}/editions/${id}`,{signal:controller.signal}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[sid,id]);
 return <dialog ref={ref} className="admin-edition-dialog" onCancel={e=>{e.preventDefault();onClose();}} aria-label="발행본 미리보기"><div className="admin-panel-title"><h2>발행본 미리보기</h2><button className="icon-button" onClick={onClose} aria-label="미리보기 닫기"><X size={20}/></button></div>{error?<p className="auth-error" role="alert">{error}</p>:data?<iframe title="구독 발행본" sandbox="allow-popups allow-popups-to-escape-sandbox" referrerPolicy="no-referrer" srcDoc={data.html}/>:<div className="empty"><Loader2 className="spin"/>발행본을 불러오는 중입니다.</div>}</dialog>;
}
function History({sid}){
 const [data,setData]=useState(null),[offset,setOffset]=useState(0),[error,setError]=useState(''),[preview,setPreview]=useState(null),[retry,setRetry]=useState(0);
 useEffect(()=>{const c=new AbortController();setData(null);setError('');authRequest(`/admin/subscriptions/${sid}/history?offset=${offset}`,{signal:c.signal}).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[sid,offset,retry]);
 const states={running:'진행 중',completed:'완료',failed:'실패',skipped:'건너뜀',review:'확인 필요'};
 if(error)return <div className="auth-error" role="alert">{error}<button className="button" onClick={()=>setRetry(n=>n+1)}>다시 불러오기</button></div>;
 if(!data)return <div className="empty"><Loader2 className="spin"/>발행 이력을 불러오는 중입니다.</div>;
 return <><h3>전달된 뉴스레터 <span className="count">{data.delivered_total}</span></h3><div className="admin-table-scroll"><table><thead><tr><th>발송 시각</th><th>수집 기간</th><th>기사 수</th><th>보기</th></tr></thead><tbody>{data.delivered.map(r=><tr key={r.newsletter_id}><td>{timestamp(r.created_at)}</td><td>{r.coverage_start_date} ~ {r.coverage_end_date}</td><td>{r.article_count}</td><td><button className="icon-button" aria-label={`${r.coverage_end_date} 발행본 보기`} onClick={()=>setPreview(r.newsletter_id)}><Eye size={17}/></button></td></tr>)}</tbody></table>{!data.delivered.length&&<div className="empty">전달된 뉴스레터가 없습니다.</div>}</div>
 <h3 className="admin-history-heading">자동 발행 실행 이력 <span className="count">{data.total}</span></h3><div className="admin-table-scroll"><table><thead><tr><th>예정일</th><th>상태</th><th>시도</th><th>메일 성공 / 실패 / 불명</th><th>보기</th></tr></thead><tbody>{data.jobs.map(r=><tr key={r.job_id}><td>{r.scheduled_date}</td><td><span className={'admin-status '+r.status}>{states[r.status]||r.status}</span></td><td>{r.attempt}</td><td>{r.mail_status==='processing'?'처리 중':`${r.delivery.sent} / ${r.delivery.failed} / ${r.delivery.unknown}`}</td><td>{r.newsletter_id&&<button className="icon-button" aria-label={`${r.scheduled_date} 생성본 보기`} onClick={()=>setPreview(r.newsletter_id)}><Eye size={17}/></button>}</td></tr>)}</tbody></table>{!data.jobs.length&&<div className="empty">발행 실행 기록이 없습니다.</div>}</div>
 <div className="admin-pagination"><span>50건씩 조회 · {offset/50+1} 페이지</span><button className="button" disabled={!offset} onClick={()=>setOffset(n=>Math.max(0,n-50))}>이전</button><button className="button" disabled={offset+50>=Math.max(data.total,data.delivered_total)} onClick={()=>setOffset(n=>n+50)}>다음</button></div>{preview&&<Preview sid={sid} id={preview} onClose={()=>setPreview(null)}/>}</>;
}
function Detail({sid,onSaved,onDirtyChange}){
 const [data,setData]=useState(null),[form,setForm]=useState(null),[members,setMembers]=useState([]),[tab,setTab]=useState('members'),[picker,setPicker]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 const [query,setQuery]=useState(''),[domain,setDomain]=useState('');
 const apply=d=>{setData(d);setForm(formFrom(d));setMembers(d.members);};
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');authRequest(`/admin/subscriptions/${sid}`,{signal:c.signal}).then(d=>{if(!c.signal.aborted)apply(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[sid,retry]);
 const membersDirty=data&&JSON.stringify(members.map(bodyMember))!==JSON.stringify(data.members.map(bodyMember));
 const formDirty=data&&JSON.stringify(form)!==JSON.stringify(formFrom(data));
 const dirty=membersDirty||formDirty;
 useEffect(()=>{onDirtyChange(Boolean(dirty));return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
 useEffect(()=>{const fn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
 async function save(kind){setBusy(true);setError('');setMessage('');try{const payload=kind==='members'?{members:members.map(bodyMember),revision:data.revision}:{...form,revision:data.revision};const d=await authRequest(`/admin/subscriptions/${sid}/${kind}`,{method:'PUT',body:JSON.stringify(payload)});setData(d);if(kind==='members')setMembers(d.members);else setForm(formFrom(d));setMessage(kind==='members'?'구독자를 저장했습니다.':'발행 정보를 저장했습니다.');onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}
 function addQuery(){const v=query.trim().replace(/\s+/g,' ');if(!v)return;if(form.queries.some(q=>q.toLowerCase()===v.toLowerCase())){setError('이미 추가한 쿼리입니다.');return;}if(form.queries.length>=5){setError('쿼리는 최대 5개입니다.');return;}setForm({...form,queries:[...form.queries,v]});setQuery('');setError('');}
 function addDomain(){try{const u=new URL(domain.includes('://')?domain:`https://${domain}`);const host=u.hostname.toLowerCase().replace(/^www\./,'');if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.port||!host.includes('.'))throw Error();if(form.domains.includes(host)){setError('이미 추가한 도메인입니다.');return;}setForm({...form,domains:[...form.domains,host].sort()});setDomain('');setError('');}catch{setError('올바른 도메인을 입력해 주세요.');}}
 if(loading)return <section className="admin-panel"><div className="empty"><Loader2 className="spin"/>구독 정보를 불러오는 중입니다.</div></section>;
 if(!data)return <section className="admin-panel"><p role="alert" className="auth-error">{error}</p><button className="button" onClick={()=>setRetry(n=>n+1)}>다시 불러오기</button></section>;
 return <section className="admin-panel admin-sub-detail"><div className="admin-panel-title"><div><span className="eyebrow">SUBSCRIPTION</span><h2>{data.name}</h2><p>{data.topic}</p><small>개설자 {data.owner_name} · {data.owner_employee_id} · {schedule(data)} 오전 8시</small></div><button className="icon-button" disabled={busy} title="구독 정보 새로고침" aria-label="구독 정보 새로고침" onClick={()=>{if(!dirty||window.confirm('저장하지 않은 변경을 버리고 새로고침하시겠습니까?'))setRetry(n=>n+1);}}><RefreshCw size={17}/></button></div>
 <div className="admin-tabs" role="tablist" aria-label="구독 관리 항목">{[['members','구독자 관리',Users],['history','발행 히스토리',CalendarDays],['settings','발행 정보',SlidersHorizontal]].map(([key,label,Icon])=><button role="tab" aria-selected={tab===key} key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setMessage('');}}><Icon size={15}/>{label}</button>)}</div>
 {error&&<p role="alert" className="auth-error">{error}</p>}{message&&<p role="status" className="account-success">{message}</p>}
 {tab==='members'&&<><div className="admin-panel-title"><h3>수신 멤버 <span className="count">{members.length}</span></h3><button className="button" disabled={busy} onClick={()=>setPicker(true)}><Plus size={16}/>구독자 추가</button></div><div className="admin-table-scroll"><table><thead><tr><th>구독자</th><th>구분 / 팀</th><th>수신 상태</th><th>삭제</th></tr></thead><tbody>{members.map(m=><tr key={identity(m)}><td><strong>{m.full_name}</strong><small>{m.email||m.email_address}</small></td><td>{m.member_type==='external'?'기타':m.team_name||'임직원'}</td><td><button type="button" className={'admin-member-toggle '+(m.status!=='paused'?'on':'')} aria-label={`${m.full_name} 수신 상태`} aria-pressed={m.status!=='paused'} disabled={busy} onClick={()=>setMembers(ms=>ms.map(v=>identity(v)===identity(m)?{...v,status:v.status==='paused'?'active':'paused'}:v))}>{m.status==='paused'?'일시정지':'수신 중'}</button></td><td><button className="icon-button" disabled={busy} aria-label={`${m.full_name} 구독자 삭제`} onClick={()=>setMembers(ms=>ms.filter(v=>identity(v)!==identity(m)))}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!members.length&&<div className="empty">등록된 구독자가 없습니다.</div>}</div><p className="admin-note">수신을 정지하거나 멤버를 삭제하면 이후 발송 대상에서 제외됩니다. 저장 버튼을 눌러 적용하세요.</p><div className="admin-save-bar"><span>{membersDirty?'저장하지 않은 변경 사항이 있습니다.':'현재 구독자 정보'}</span><button className="button primary" disabled={busy||!membersDirty} onClick={()=>save('members')}>{busy?<Loader2 size={16} className="spin"/>:null}구독자 저장</button></div></>}
 {tab==='history'&&<History sid={sid}/>}
 {tab==='settings'&&<form onSubmit={e=>{e.preventDefault();if(query.trim()||domain.trim()){setError('입력 중인 쿼리·도메인을 추가하거나 비운 뒤 저장해 주세요.');return;}save('settings');}}><fieldset disabled={busy} className="admin-settings-fieldset"><div className="admin-sub-fields"><label>구독 이름<input required maxLength={80} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>발행 주기<select aria-label="발행 주기" value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="daily">일간</option><option value="weekly">주간</option><option value="monthly">월간</option></select></label><label>발행 시작일<input type="date" required value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></label></div>
 {form.frequency==='weekly'&&<div className="admin-weekdays"><span>발행 요일</span>{days.map((d,i)=><button type="button" aria-pressed={form.weekdays.includes(i)} key={i} onClick={()=>setForm({...form,weekdays:form.weekdays.includes(i)?form.weekdays.filter(v=>v!==i):[...form.weekdays,i].sort()})}>{d}</button>)}</div>}{form.frequency==='monthly'&&<label className="admin-month-day">매월 발행일<input type="number" required min={1} max={31} value={form.month_day} onChange={e=>setForm({...form,month_day:Number(e.target.value)})}/>일 <small>해당 일이 없는 달에는 말일 발행</small></label>}<p className="admin-note">발행 시각은 오전 8시(KST)입니다. 변경된 일정은 저장 이후 자동 실행에 적용됩니다.</p>
 <div className="admin-shared-note"><strong>공유 수집 조건 · 활성 구독 {data.shared_subscriptions.length}개</strong><p>아래 쿼리·도메인은 같은 샘플을 사용하는 구독에 함께 적용됩니다. 이미 수집된 기사와 발행본은 유지됩니다.</p><div>{data.shared_subscriptions.map(s=><span key={s.subscription_id}>{s.name} · {s.owner_name}</span>)}</div></div>
 <h3>검색 쿼리 <span className="count">{form.queries.length} / 5</span></h3><div className="admin-source-list">{form.queries.map((q,i)=><div key={i}><input aria-label={`검색 쿼리 ${i+1}`} required maxLength={400} value={q} onChange={e=>setForm({...form,queries:form.queries.map((v,j)=>i===j?e.target.value:v)})}/><button type="button" className="icon-button" aria-label={`검색 쿼리 ${i+1} 삭제`} onClick={()=>setForm({...form,queries:form.queries.filter((_,j)=>j!==i)})}><X size={16}/></button></div>)}</div><div className="admin-source-add"><input aria-label="새 검색 쿼리" maxLength={400} placeholder="검색 쿼리 입력" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addQuery();}}}/><button className="button" type="button" disabled={form.queries.length>=5||!query.trim()} onClick={addQuery}>추가</button></div>
 <h3>수집 도메인 <span className="count">{form.search_all_domains?'전체':form.domains.length}</span></h3><label className="admin-all-domains"><input type="checkbox" checked={form.search_all_domains} onChange={e=>{setForm({...form,search_all_domains:e.target.checked});setDomain('');}}/>전체 도메인 검색</label>{!form.search_all_domains&&<><div className="admin-domain-chips">{form.domains.map(d=><span key={d}>{d}<button type="button" aria-label={`${d} 도메인 삭제`} onClick={()=>setForm({...form,domains:form.domains.filter(v=>v!==d)})}><X size={14}/></button></span>)}</div><div className="admin-source-add"><input aria-label="새 도메인" placeholder="example.com" maxLength={300} value={domain} onChange={e=>setDomain(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addDomain();}}}/><button className="button" type="button" disabled={!domain.trim()||form.domains.length>=100} onClick={addDomain}>추가</button></div></>}
 <div className="admin-save-bar"><span>{formDirty?'저장하지 않은 변경 사항이 있습니다.':'현재 발행 정보'}</span><button className="button primary" disabled={busy||!formDirty}>{busy?<Loader2 className="spin" size={16}/>:null}발행 정보 저장</button></div></fieldset></form>}
 {picker&&<RecipientSearchDialog newsletter={{title:data.name}} directoryPath="/admin/subscriptions/directory" initialRecipients={members} onClose={()=>setPicker(false)} onSelect={selected=>{setMembers(selected.map(m=>({...m,status:members.find(v=>identity(v)===identity(m))?.status||'active'})));setPicker(false);}}/>}
 </section>;
}
export default function AdminSubscriptions(){
 const [dirty,setDirty]=useState(false);
 const [rows,setRows]=useState([]),[sid,setSid]=useState(null),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');authRequest('/admin/subscriptions',{signal:c.signal}).then(d=>{if(!c.signal.aborted){setRows(d);setSid(current=>d.some(s=>s.subscription_id===current)?current:d[0]?.subscription_id||null);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[revision]);
 const visible=rows.filter(r=>`${r.name} ${r.topic} ${r.owner_name} ${r.owner_employee_id}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="admin-page"><div className="page-heading"><div><div className="eyebrow">SUBSCRIPTION MANAGEMENT</div><h1>구독 관리</h1><p>활성 구독의 수신 멤버와 발행 이력, 수집 조건을 관리하세요.</p></div><button className="button" disabled={loading} onClick={()=>setRevision(n=>n+1)}><RefreshCw size={16}/>새로고침</button></div>{error&&<p className="auth-error" role="alert">{error}</p>}<div className="admin-sub-layout"><aside className="admin-sub-list"><div className="admin-sub-search"><Search size={17}/><input aria-label="활성 구독 검색" placeholder="구독 이름, 주제, 개설자 검색" value={search} onChange={e=>setSearch(e.target.value)}/></div><p>활성 구독 {rows.length}개</p><div className="admin-sub-cards">{visible.map(r=><button key={r.subscription_id} className={sid===r.subscription_id?'selected':''} onClick={()=>{if(sid===r.subscription_id)return;if(!dirty||window.confirm('저장하지 않은 변경을 버리고 다른 구독을 여시겠습니까?'))setSid(r.subscription_id);}}><span className="admin-sub-card-top"><Radio size={16}/>{schedule(r)}</span><strong>{r.name}</strong><span>{r.topic}</span><small>{r.owner_name} · 수신 {r.active_member_count}/{r.member_count}명 · 발행 {r.issued_count}회</small></button>)}{!visible.length&&<div className="empty">{loading?'불러오는 중입니다.':'활성 구독이 없습니다.'}</div>}</div></aside><div className="admin-sub-content">{sid?<Detail key={sid} sid={sid} onDirtyChange={setDirty} onSaved={()=>setRevision(n=>n+1)}/>:<section className="admin-panel"><div className="empty"><Users size={28}/>관리할 구독을 선택하세요.</div></section>}</div></div></main>;
}
