import React, {useEffect, useState} from 'react';
import {MessageSquareText, Radio, Activity, Coins, Users, Layers3, UserRound, ChevronRight, LogOut, RefreshCw, Loader2, Settings2, X} from 'lucide-react';
import AdminFeedback from './AdminFeedback';
import AdminSelect from './AdminSelect';
import AdminSubscriptions from './AdminSubscriptions';
import AccountManagement from './AccountManagement';
import {authRequest} from './authApi';
import './admin.css';

const number=n=>Number(n||0).toLocaleString('ko-KR');
const money=n=>'$'+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:4,maximumFractionDigits:4});
const dateTime=s=>s?new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'—';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const initialRange=()=>{const end=today();const d=new Date(end+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-29);return {start:d.toISOString().slice(0,10),end};};
const labels={completed:'완료',running:'진행 중',failed:'실패',cancelled:'취소',draft:'작성 중',skipped:'건너뜀',review:'확인 필요'};
const steps={sample_article_preprocessing:'샘플 기사 전처리',subscription_article_preprocessing:'구독 기사 전처리',sample_issue_scoring:'샘플 기사 평가',subscription_article_scoring:'구독 기사 평가',issue_scoring:'기사 평가',sample_domain_recommendation:'샘플 도메인 추천',sample_query_recommendation:'샘플 쿼리 추천',sample_newsletter_summary:'샘플 핵심 요약',subscription_newsletter_summary:'구독 핵심 요약',subscription_issue_selection:'구독 기사 선정',subject_validation:'주제 확인'};
const stepLabel=s=>steps[s]||s;
function Table({headers,children,empty=false}){return <div className="admin-table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table>{empty&&<div className="empty">해당 기간의 기록이 없습니다.</div>}</div>;}
function Card({label,value,note}){return <div className="admin-stat"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>;}
function Panel({title,help,children}){return <section className="admin-panel"><div className="admin-panel-title"><h2>{title}</h2>{help&&<small>{help}</small>}</div>{children}</section>;}
function Operations({data}){
 const {snapshot:s,jobs,delivery:d,activity,errors,error_count}=data;
 return <><div className="admin-stats"><Card label="활성 일반 계정" value={number(s.users)} note="현재 기준"/><Card label="보관된 샘플" value={number(s.samples)} note="현재 기준"/><Card label="활성 구독" value={number(s.subscriptions)} note="현재 기준"/><Card label="수신 중 멤버" value={number(s.members)} note="구독별 멤버 합계 · 중복 포함"/></div>
 <div className="admin-columns">{[['samples','샘플 생성'],['collection','자동 기사 수집'],['publication','구독 발행']].map(([key,title])=><Panel key={key} title={title} help="선택 기간 내 시작된 작업"><div className="admin-job-total">{number(jobs[key].reduce((n,r)=>n+r.count,0))}<small>건</small></div><div className="admin-status-list">{jobs[key].length?jobs[key].map(r=><div key={r.status}><span className={'admin-status '+r.status}>{labels[r.status]||r.status}</span><strong>{number(r.count)}</strong></div>):<p>기록 없음</p>}</div></Panel>)}</div>
 <div className="admin-stats"><Card label="메일 발송 요청" value={number(d.messages)} note={`처리 중 ${number(d.processing)}건`}/><Card label="수신자별 발송 성공" value={number(d.sent)} note="수신함 도착·열람 여부는 포함하지 않음"/><Card label="발송 실패 / 결과 불명" value={`${number(d.failed)} / ${number(d.unknown)}`} note="수신자별 결과"/><Card label="기록된 오류" value={number(error_count)} note="선택 기간 기준"/></div>
 <Panel title="사용자별 이용 현황" help="샘플·LLM은 선택 기간, 구독·최근 로그인은 현재 기준"><Table headers={['사용자','소속 팀','샘플 실행','LLM 호출','생성한 구독','최근 로그인']} empty={!activity.length}>{activity.map(r=><tr key={r.user_id}><td><strong>{r.full_name}</strong><small>{r.employee_id}</small></td><td>{r.team_name}</td><td>{number(r.samples)}</td><td>{number(r.calls)}</td><td>{number(r.subscriptions)}</td><td>{dateTime(r.last_login_at)}</td></tr>)}</Table></Panel>
 <Panel title="최근 오류" help="선택 기간 내 최근 100건"><Table headers={['시각','사용자','단계','유형','오류 내용']} empty={!errors.length}>{errors.map(r=><tr key={r.error_id}><td>{dateTime(r.created_at)}</td><td>{r.full_name||'시스템'}</td><td>{stepLabel(r.step)}</td><td>{r.error_type}</td><td className="admin-message">{r.message}</td></tr>)}</Table></Panel></>;
}
function Pricing({data,onSaved,onClose}){
 const [values,setValues]=useState(()=>data.options.models.map(m=>({...m,...(data.prices.find(p=>p.provider===m.provider&&p.model===m.model)||{input_rate:'',cached_rate:'',output_rate:''})})));
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [saved,setSaved]=useState('');
 async function save(row){setBusy(true);setError('');setSaved('');try{await authRequest('/admin/llm-pricing',{method:'PUT',body:JSON.stringify({...row,input_rate:Number(row.input_rate),cached_rate:Number(row.cached_rate),output_rate:Number(row.output_rate)})});setSaved(row.model+' 단가를 저장했습니다.');onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const ref=React.useRef(null);useEffect(()=>{const focus=document.activeElement;ref.current.showModal();return()=>focus?.focus();},[]);
 return <dialog ref={ref} className="admin-pricing-dialog" onCancel={e=>{e.preventDefault();if(!busy)onClose();}} aria-labelledby="pricing-title"><div className="admin-panel-title"><h2 id="pricing-title">모델별 비용 단가</h2><button className="icon-button" disabled={busy} onClick={onClose} aria-label="닫기"><X size={20}/></button></div><p>100만 토큰당 USD 단가를 입력하세요. 저장한 단가로 조회 기간 전체의 비용을 다시 추정합니다.</p><p>입력 토큰에서 캐시 토큰을 제외해 계산합니다. 캐시 기록이 없으면 일반 입력 단가를 적용합니다. 실제 청구 금액과 다를 수 있습니다.</p>{error&&<p className="auth-error" role="alert">{error}</p>}{saved&&<p role="status" className="account-success">{saved}</p>}
 {values.length===0&&<div className="empty">LLM 사용 기록이 있는 모델이 없습니다.</div>}{values.map((r,i)=><form className="admin-price-row" key={r.provider+r.model} onSubmit={e=>{e.preventDefault();save(r);}}><strong>{r.model}<small>{r.provider}</small></strong>{[['input_rate','입력'],['cached_rate','캐시 입력'],['output_rate','출력']].map(([key,label])=><label key={key}>{label}<input aria-label={`${r.model} ${label} 단가`} type="number" min="0" max="100000" step="any" required disabled={busy} value={r[key]} onChange={e=>setValues(v=>v.map((x,j)=>j===i?{...x,[key]:e.target.value}:x))}/></label>)}<button className="button primary" disabled={busy}>저장</button></form>)}</dialog>;
}
function Tokens({data,offset,setOffset}){
 const [group,setGroup]=useState('steps');const s=data.summary;const max=Math.max(1,...data.groups.daily.map(d=>d.total_tokens));
 return <><div className="admin-stats admin-token-stats"><Card label="Exa Search 뉴스" value={number(data.exa_search_results)} note={<>중복 포함 · 기간·사용자·구독 기준<br/>과거 샘플 검색량 미기록</>}/><Card label="LLM 호출" value={number(s.calls)} note={`토큰 기록 불완전 ${number(s.unknown_usage)}건`}/><Card label="전체 토큰" value={number(s.total_tokens)} note={`입력 ${number(s.input_tokens)} · 출력 ${number(s.output_tokens)}`}/><Card label="캐시 입력 토큰" value={number(s.cached_input_tokens)} note="입력 토큰에 포함"/><Card label="비용 추정 (USD)" value={s.priced_calls?money(s.cost):'—'} note={`계산 ${number(s.priced_calls)}건 · 제외 ${number(s.calls-s.priced_calls)}건`}/></div>
 <Panel title="일별 토큰 사용량" help="한국 시간 기준 · 기록이 있는 날짜"><div className="admin-chart">{data.groups.daily.length?data.groups.daily.map(d=><div className="admin-bar-row" key={d.key}><span>{d.label}</span><div><i style={{width:`${d.total_tokens/max*100}%`}}/></div><strong>{number(d.total_tokens)}</strong></div>):<div className="empty">사용 기록이 없습니다.</div>}</div></Panel>
 <Panel title="사용량 상세 분석" help="비용은 단가와 입·출력 기록이 모두 있는 호출만 합산"><div className="admin-tabs">{[['steps','처리 단계별'],['users','사용자별'],['models','모델별'],['subscriptions','활성 구독별']].map(([key,label])=><button key={key} className={group===key?'active':''} onClick={()=>setGroup(key)}>{label}</button>)}</div>{group==='subscriptions'&&<p className="admin-note">같은 샘플의 수집·평가·발행 호출을 공유하는 구독에는 동일 사용량이 표시됩니다. 구독 행끼리 합산하지 않으며 전체 합계는 호출당 한 번만 계산합니다. 과거 연결 불명 호출 {number(data.unlinked_subscription_calls)}건은 구독별 집계에서 제외됩니다.</p>}<Table headers={['구분','호출','입력','출력','캐시 입력','비용 (USD)','비용 계산 / 전체']} empty={!data.groups[group].length}>{data.groups[group].map(r=><tr key={r.key}><td>{group==='steps'?stepLabel(r.label):r.label}</td><td>{number(r.calls)}</td><td>{number(r.input_tokens)}</td><td>{number(r.output_tokens)}</td><td>{number(r.cached_input_tokens)}</td><td>{r.priced_calls?money(r.cost):'—'}</td><td>{r.priced_calls} / {r.calls}</td></tr>)}</Table></Panel>
 <Panel title="LLM 호출 기록" help="최신순 · 50건씩"><Table headers={['시작 시각','사용자','처리 단계 / 모델','입력 / 출력','소요 시간','비용 (USD)','기록 상태']} empty={!data.requests.length}>{data.requests.map(r=><tr key={r.request_id}><td title={r.request_id}>{dateTime(r.started_at)}</td><td>{r.full_name}</td><td>{stepLabel(r.step)}<small>{r.provider} / {r.model}</small></td><td>{r.input_tokens==null?'—':number(r.input_tokens)} / {r.output_tokens==null?'—':number(r.output_tokens)}</td><td>{r.duration_ms==null?'—':(r.duration_ms/1000).toFixed(1)+'초'}</td><td>{r.cost==null?'—':money(r.cost)}</td><td>{r.has_error?'오류 기록':r.completed_at?'종료':'종료 기록 없음'}</td></tr>)}</Table><div className="admin-pagination"><span>{number(s.calls)}건 중 {s.calls?offset+1:0}–{Math.min(offset+50,s.calls)}</span><button className="button" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-50))}>이전</button><button className="button" disabled={offset+50>=s.calls} onClick={()=>setOffset(offset+50)}>다음</button></div></Panel></>;
}
function Dashboard({mode}){
 const [range,setRange]=useState(initialRange);const [filters,setFilters]=useState({user_id:'',step:'',model:'',provider:'',subscription_id:''});const [offset,setOffset]=useState(0);
 const [data,setData]=useState(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [revision,setRevision]=useState(0);const [pricing,setPricing]=useState(false);
 const valid=range.start&&range.end&&range.end>=range.start&&(new Date(range.end)-new Date(range.start))/86400000<=365;
 useEffect(()=>{if(!valid){setLoading(false);return;}const controller=new AbortController();setLoading(true);setError('');authRequest(`/admin/${mode}?`+new URLSearchParams({...range,...(mode==='tokens'?filters:{}),offset}),{signal:controller.signal}).then(d=>{if(!controller.signal.aborted)setData(d);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[mode,range,filters,offset,revision,valid]);
 function updateFilter(key,value){setFilters(f=>({...f,[key]:value}));setOffset(0);}
 return <main className="admin-page"><div className="page-heading"><div><div className="eyebrow">{mode==='tokens'?'LLM USAGE & COST':'SERVICE OPERATIONS'}</div><h1>{mode==='tokens'?'토큰 관리':'운영 관리'}</h1><p>{mode==='tokens'?'호출 단계와 모델별 사용량을 확인하고 운영 비용을 관리하세요.':'사용자 활동과 뉴스레터 수집·발행·발송 현황을 확인하세요.'}</p></div><div className="admin-heading-actions">{mode==='tokens'&&data&&<button className="button" onClick={()=>setPricing(true)}><Settings2 size={16}/>단가 설정</button>}<button className="button" disabled={loading} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={16}/>새로고침</button></div></div>
 <div className="admin-filters"><label>시작일<input type="date" value={range.start} onChange={e=>{setRange({...range,start:e.target.value});setOffset(0);}}/></label><span>—</span><label>종료일<input type="date" value={range.end} onChange={e=>{setRange({...range,end:e.target.value});setOffset(0);}}/></label><button className="button" onClick={()=>{setRange(initialRange());setOffset(0);}}>최근 30일</button>
 {mode==='tokens'&&data&&<div className="admin-token-selects">
 <AdminSelect label="활성 구독" value={filters.subscription_id} onChange={value=>updateFilter('subscription_id',value)} options={[{value:'',label:'전체 호출'},...(data.options.subscriptions||[]).map(s=>({value:s.subscription_id,label:s.name,description:s.owner_name}))]}/>
 <AdminSelect label="사용자" value={filters.user_id} onChange={value=>updateFilter('user_id',value)} options={[{value:'',label:'전체 사용자'},...data.options.users.map(u=>({value:u.user_id,label:u.full_name,description:u.employee_id}))]}/>
 <AdminSelect label="처리 단계" value={filters.step} onChange={value=>updateFilter('step',value)} options={[{value:'',label:'전체 단계'},...data.options.steps.map(s=>({value:s,label:stepLabel(s)}))]}/>
 <AdminSelect label="모델" value={JSON.stringify([filters.provider,filters.model])} onChange={value=>{const [provider,model]=JSON.parse(value);setFilters(f=>({...f,provider,model}));setOffset(0);}} options={[{value:'["",""]',label:'전체 모델'},...data.options.models.map(m=>({value:JSON.stringify([m.provider,m.model]),label:m.model,description:m.provider}))]}/>
 </div>}
 </div>{mode==='tokens'&&filters.subscription_id&&<p className="admin-note">선택한 구독과 동일 샘플의 공통 수집·평가·발행 호출을 조회합니다. 샘플 생성 단계의 호출은 포함하지 않습니다.</p>}{!valid?<p className="auth-error" role="alert">시작일 이후 최대 366일의 기간을 선택해 주세요.</p>:error?<p className="auth-error" role="alert">{error}</p>:loading?<div className="empty" role="status"><Loader2 className="spin"/>현황을 불러오고 있습니다.</div>:data&&(mode==='tokens'?<Tokens data={data} offset={offset} setOffset={setOffset}/>:<Operations data={data}/>)}
 {pricing&&data&&<Pricing data={data} onClose={()=>setPricing(false)} onSaved={()=>setRevision(v=>v+1)}/>}</main>;
}
export default function AdminWorkspace({user,onLogout}){
 const [view,setView]=useState('accounts');const nav=[['accounts','계정 관리',Users],['operations','운영 관리',Activity],['tokens','토큰 관리',Coins],['subscriptions','구독 관리',Radio],['feedback','피드백 관리',MessageSquareText]];const title=nav.find(n=>n[0]===view)[1];
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-icon"><Layers3 size={24}/></span><div>WiaNews<small>ADMIN WORKSPACE</small></div></div><div className="workspace-label">ADMINISTRATION</div><nav>{nav.map(([key,label,Icon])=><button key={key} className={view===key?'active':''} aria-current={view===key?'page':undefined} onClick={()=>setView(key)}><Icon size={17}/>{label}<ChevronRight size={14}/></button>)}</nav><div className="side-bottom"><div className="profile"><span><UserRound size={20}/></span><div>{user.full_name}<small>관리자</small></div></div><button className="sidebar-logout" onClick={onLogout}><LogOut size={16}/>로그아웃</button></div></aside><div className="main-shell"><header className="topbar"><div>Workspace<ChevronRight size={13}/><strong>{title}</strong></div><span className="demo-badge">관리자</span></header>{view==='accounts'?<AccountManagement user={user} onLogout={onLogout}/>:view==='feedback'?<AdminFeedback/>:view==='subscriptions'?<AdminSubscriptions/>:<Dashboard key={view} mode={view}/>}</div></div>;
}
