import React,{useEffect,useRef,useState} from 'react';
import {X,Loader2,Mail,Plus,Check} from 'lucide-react';
import {authRequest,postAuth} from './authApi';

export default function FeedbackApply({item,onClose,onDone}){
 const ref=useRef(null),request=useRef(null);
 const [data,setData]=useState(null),[sources,setSources]=useState(null),[query,setQuery]=useState(''),[domain,setDomain]=useState(''),[response,setResponse]=useState('');
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>previous?.focus();},[]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setLoadError('');
 if(!item.subscription_id){setLoadError('원본 구독이 없어 반영할 수 없습니다.');setLoading(false);return()=>c.abort();}
 authRequest(`/admin/subscriptions/${item.subscription_id}`,{signal:c.signal}).then(d=>{if(!c.signal.aborted){setData(d);setSources({revision:d.revision,queries:d.queries,domains:d.domains,search_all_domains:d.search_all_domains});}}).catch(e=>{if(!c.signal.aborted)setLoadError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[item.subscription_id,retry]);
 function addQuery(){const q=query.trim().replace(/\s+/g,' ');if(!q)return;if(sources.queries.some(v=>v.toLowerCase()===q.toLowerCase())){setError('이미 추가한 쿼리입니다.');return;}setSources({...sources,queries:[...sources.queries,q]});setQuery('');setError('');}
 function addDomain(){try{const u=new URL(domain.includes('://')?domain:`https://${domain}`),host=u.hostname.toLowerCase().replace(/^www\./,'');if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.port||!host.includes('.'))throw Error();if(sources.domains.includes(host)){setError('이미 추가한 도메인입니다.');return;}setSources({...sources,domains:[...sources.domains,host].sort()});setDomain('');setError('');}catch{setError('올바른 도메인을 입력해 주세요.');}}
 async function submit(e){e.preventDefault();if(busy||!sources)return;setError('');if(query.trim()||domain.trim()){setError('입력 중인 쿼리·도메인을 추가하거나 비운 뒤 반영해 주세요.');return;}
 const payload={revision:item.revision,status:'completed',response:response.trim(),sources};const key=JSON.stringify(payload);
 if(request.current?.key!==key)request.current={key,body:{...payload,request_id:crypto.randomUUID()}};
 setBusy(true);try{onDone(await postAuth(`/admin/feedback/${item.feedback_id}/decision`,request.current.body));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <dialog ref={ref} className="feedback-dialog feedback-apply-dialog" aria-labelledby="feedback-apply-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="feedback-dialog-head"><div><h2 id="feedback-apply-title">피드백 반영</h2><p>{item.subscription_name}</p></div><button className="icon-button" aria-label="반영 창 닫기" disabled={busy} onClick={onClose}><X size={20}/></button></div><div className="feedback-apply-request"><strong>요청 내용</strong><p>{item.content}</p></div>
 {loading?<div className="empty"><Loader2 className="spin"/>현재 수집 조건을 불러오는 중입니다.</div>:loadError?<div className="auth-error" role="alert">{loadError}<button className="button" onClick={()=>setRetry(v=>v+1)}>다시 불러오기</button></div>:data&&<form onSubmit={submit}><fieldset className="admin-settings-fieldset" disabled={busy}><div className="admin-shared-note"><strong>공유 수집 조건 · 활성 구독 {data.shared_subscriptions.length}개</strong><p>현재 저장된 조건을 수정합니다. 같은 샘플을 사용하는 구독에도 함께 적용됩니다.</p><div>{data.shared_subscriptions.map(s=><span key={s.subscription_id}>{s.name} · {s.owner_name}</span>)}</div></div>
 <h3>검색 쿼리 <span className="count">{sources.queries.length} / 5</span></h3><div className="admin-source-list">{sources.queries.map((q,i)=><div key={i}><input aria-label={`반영 검색 쿼리 ${i+1}`} required maxLength={400} value={q} onChange={e=>setSources({...sources,queries:sources.queries.map((v,j)=>j===i?e.target.value:v)})}/><button className="icon-button" type="button" aria-label={`반영 검색 쿼리 ${i+1} 삭제`} onClick={()=>setSources({...sources,queries:sources.queries.filter((_,j)=>i!==j)})}><X size={16}/></button></div>)}</div><div className="admin-source-add"><input aria-label="추가할 검색 쿼리" placeholder="추가할 검색 쿼리" maxLength={400} value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();if(sources.queries.length<5)addQuery();}}}/><button type="button" className="button" disabled={!query.trim()||sources.queries.length>=5} onClick={addQuery}><Plus size={15}/>추가</button></div>
 <h3>수집 도메인 <span className="count">{sources.search_all_domains?'전체':sources.domains.length}</span></h3><label className="admin-all-domains"><input type="checkbox" checked={sources.search_all_domains} onChange={e=>{setSources({...sources,search_all_domains:e.target.checked});setDomain('');}}/>전체 도메인 검색</label>{!sources.search_all_domains&&<><div className="admin-domain-chips">{sources.domains.map(d=><span key={d}>{d}<button type="button" aria-label={`${d} 반영 도메인 삭제`} onClick={()=>setSources({...sources,domains:sources.domains.filter(v=>v!==d)})}><X size={14}/></button></span>)}</div><div className="admin-source-add"><input aria-label="추가할 도메인" placeholder="example.com" maxLength={300} value={domain} onChange={e=>setDomain(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();if(sources.domains.length<100)addDomain();}}}/><button type="button" className="button" disabled={!domain.trim()||sources.domains.length>=100} onClick={addDomain}><Plus size={15}/>추가</button></div></>}
 <label className="feedback-input">반영 내용<textarea required maxLength={3000} rows={3} value={response} onChange={e=>setResponse(e.target.value)} placeholder="요청자에게 안내할 변경 내용과 이유를 적어 주세요."/></label><p className="feedback-recipient"><Mail size={16}/>{item.requester_name} · {item.requester_email}</p><p className="admin-note">저장하면 수집 조건과 피드백 상태를 함께 반영하고 결과 메일을 발송합니다.</p>{error&&<p className="auth-error" role="alert">{error}</p>}<footer className="feedback-actions"><button type="button" className="button" onClick={onClose}>취소</button><button className="button primary" disabled={!response.trim()||!sources.queries.length||(!sources.search_all_domains&&!sources.domains.length)}>{busy?<Loader2 size={16} className="spin"/>:<Check size={16}/>}반영 및 메일 발송</button></footer></fieldset></form>}</dialog>;
}
