import React from 'react';
import {ArrowRight,ArrowUpRight,Layers3,Play,Globe2,Sparkles,Mail,Search,SlidersHorizontal,CalendarDays,Presentation,Download,Check,FileText} from 'lucide-react';
import {introResources} from './introContent';
import './introduction.css';

export default function Introduction(){
 return <div className="intro-page"><header className="intro-header"><a href="#" className="intro-brand" aria-label="WiaNews 소개 처음으로"><Layers3 size={26}/><span>WiaNews</span></a><nav aria-label="서비스 소개 메뉴"><a href="#intro-how">이용 방법</a><a href="#intro-guide">사용 가이드</a><a href="#app" className="intro-nav-start">시작하기<ArrowUpRight size={15}/></a></nav></header>
 <main className="intro-main"><section className="intro-hero" aria-labelledby="intro-heading"><div className="intro-hero-copy"><div className="intro-eyebrow"><span/>HYUNDAI WIA · TECH INTELLIGENCE</div><h1 id="intro-heading">기술의 흐름을 읽는<br/>나만의 뉴스레터,<br/><em>WiaNews.</em></h1><p>관심 있는 기술은 깊게, 읽어야 할 소식은 간결하게.<br/>신뢰할 수 있는 출처에서 찾은 기술 뉴스를<br/>AI가 정리하고, 원하는 주기로 전해드립니다.</p><div className="intro-hero-actions"><a href="#app" className="intro-primary">나의 뉴스레터 시작하기<ArrowRight size={18}/></a><a href="#intro-how" className="intro-text-link">어떻게 이용하나요?<ArrowDownIcon/></a></div><div className="intro-topic-hints"><span>어떤 기술이 궁금하신가요?</span><div><span>Agentic AI</span><span>전기차 통합 열관리</span><span>로보틱스</span></div></div></div>
 <div className="intro-video-column"><div className="intro-video-topline"><span>SERVICE FILM</span><span>약 1분 30초</span></div>{introResources.videoUrl?<video className="intro-video" controls preload="metadata" aria-label="WiaNews 서비스 소개 영상"><source src={introResources.videoUrl} type="video/mp4"/>이 브라우저는 영상 재생을 지원하지 않습니다.</video>:<div className="intro-video-placeholder" aria-label="WiaNews 소개 영상 준비 중"><div className="intro-orbit orbit-one"/><div className="intro-orbit orbit-two"/><span className="intro-video-corner">WiaNews / INSIDE</span><div className="intro-film-art"><div className="intro-film-source source-a"><Globe2 size={17}/><span>TRUSTED SOURCES</span></div><div className="intro-film-letter"><div><Layers3 size={16}/><strong>WiaNews</strong><span>TECH BRIEFING</span></div><span className="intro-letter-kicker">작은 정보에서, 큰 인사이트로.</span><b>기술의 변화,<br/>한 통에 담다.</b><div className="intro-letter-rule"/><div className="intro-letter-lines"><i/><i/><i/></div><div className="intro-letter-bottom"><span><Sparkles size={12}/>CURATED BY AI</span><Check size={13}/></div></div><div className="intro-film-source source-b"><Mail size={17}/><span>YOUR NEXT INSIGHT</span></div></div><div className="intro-video-caption"><span className="intro-play-mark"><Play size={19} fill="currentColor"/></span><div><strong>90초로 만나는 WiaNews</strong><small>소개 영상 준비 중</small></div></div></div>}<p className="intro-video-foot">뉴스를 찾는 시간은 줄이고, 새로운 아이디어에 집중하세요.</p></div></section>
 <section className="intro-benefits" aria-label="WiaNews의 주요 기능">{[[Globe2,'신뢰할 수 있는 출처','주제에 맞는 검색 쿼리와 도메인'],[Sparkles,'AI가 선별한 핵심 뉴스','중복을 줄이고 기술적 중요도로 선정'],[CalendarDays,'내 일정에 맞는 구독','일간·주간·월간, 오전 8시 이메일']].map(([Icon,title,description])=><div key={title}><span><Icon size={21}/></span><div><h2>{title}</h2><p>{description}</p></div></div>)}</section>
 <section className="intro-how" id="intro-how" aria-labelledby="intro-how-heading"><div className="intro-section-head"><div><span className="intro-eyebrow">HOW IT WORKS</span><h2 id="intro-how-heading">관심 주제에서 정기 구독까지.</h2></div><p>이미 구독 중인 뉴스레터를 찾거나,<br/>나에게 필요한 주제로 직접 시작해 보세요.</p></div><div className="intro-steps">{[[Search,'01','관심 기술을 정하세요','궁금한 주제를 입력하세요. 비슷한 뉴스레터가 있다면 바로 구독하고, 없다면 새로 만들 수 있어요.','주제 탐색'],[SlidersHorizontal,'02','나에게 맞는 소식을 고르세요','AI가 추천한 쿼리·도메인으로 기사를 수집하고, 평가 점수와 요약을 보며 샘플 뉴스레터를 완성하세요.','샘플 만들기'],[Mail,'03','함께 읽을 사람을 초대하세요','발행 주기와 수신 멤버를 설정하세요. 정해진 날 아침, 기술 소식을 이메일로 받아볼 수 있어요.','뉴스레터 구독']].map(([Icon,n,title,description,tag])=><article key={n}><div className="intro-step-top"><Icon size={23}/><span>{n}</span></div><span className="intro-step-tag">{tag}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
 <section className="intro-guide" id="intro-guide" aria-labelledby="intro-guide-heading"><div className="intro-guide-icon"><Presentation size={35}/><span>PPT</span></div><div className="intro-guide-copy"><span className="intro-eyebrow">QUICK START GUIDE</span><h2 id="intro-guide-heading">처음이라면, 가이드와 함께.</h2><p>주제 설정부터 뉴스레터 구독까지.<br/>{introResources.guideUrl?'단계별 사용 방법을 담은 가이드를 내려받아 확인하세요.':'단계별 사용 방법을 담은 가이드를 준비하고 있습니다.'}</p></div>{introResources.guideUrl?<a className="intro-guide-download" href={introResources.guideUrl} download={introResources.guideFilename}><Download size={18}/>PPT 가이드 다운로드<ArrowUpRight size={16}/></a>:<div className="intro-guide-ready"><button disabled><FileText size={18}/>PPT 가이드 준비 중</button><span>등록 후 이곳에서 다운로드할 수 있습니다.</span></div>}</section>
</main>
 <footer className="intro-footer"><span><b>HYUNDAI WIA</b><i/>WiaNews</span><p>Curated by your agent, made for your next idea.</p></footer></div>;
}
function ArrowDownIcon(){return <ArrowRight size={15} style={{transform:'rotate(90deg)'}}/>;}
